using SistemaDeGerenciamento2_0.Class;
using SistemaDeGerenciamento2_0.Properties;
using System;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Windows.Forms;
using DevExpress.XtraSplashScreen;

namespace SistemaDeGerenciamento2_0.Forms
{
    public partial class frmCadastroProduto : DevExpress.XtraEditors.XtraForm
    {
        private int X = 0;
        private int Y = 0;

        private int idProduto = 0;

        //private List<GrupoClass> ListaGrupoAgrupador = new List<GrupoClass>();
        //private List<FornecedorClass> ListaForncedor = new List<FornecedorClass>();

        private frmTelaPrincipal frmTelaPrincipal;


        //public frmCadastroProduto()
        //{
        //    InitializeComponent();

        //    //PreencherComboBox();

        //    // This line of code is generated by Data Source Configuration Wizard
        //    // Fill the SqlDataSource asynchronously
        //    sqlGrupo.FillAsync();


        //}
        public frmCadastroProduto()
        {
            InitializeComponent();

            ////PreencherComboBox();

            //// This line of code is generated by Data Source Configuration Wizard
            //// Fill the SqlDataSource asynchronously
            sqlGrupo.FillAsync();


        }

        //private void PreencherComboBox()
        //{
        //var tarefa1 = Task.Run(async () =>
        //{
        //    await BuscarDadosParaPreencherComboBoxGrupo();
        //});

        //var esperador1 = tarefa1.GetAwaiter();

        //esperador1.OnCompleted(() =>
        //{
        //    PreenchimentoComboBoxGrupo();
        //});

        //var tarefa2 = Task.Run(async () =>
        //{
        //    await BuscarDadosParaPreencherComboBoxFornecedor();
        //});

        //var esperador2 = tarefa2.GetAwaiter();

        //esperador2.OnCompleted(() =>
        //{
        //    PreenchimentoComboBoxFornecedor();
        //});
        //}

        //private class GrupoClass
        //{
        //    public int IDGrupo { get; set; }
        //    public string NomeGrupo { get; set; }
        //    public string NomeAgrupador { get; set; }
        //}

        //private async Task BuscarDadosParaPreencherComboBoxGrupo()
        //{
        //    try
        //    {
        //        using (SistemaDeGerenciamento2_0Entities5 db = new SistemaDeGerenciamento2_0Entities5())
        //        {
        //            ListaGrupoAgrupador = db.tb_grupo.Where(x => !string.IsNullOrEmpty(x.gp_nome_grupo))
        //            .Select(x => new GrupoClass { IDGrupo = x.id_grupo, NomeGrupo = x.gp_nome_grupo, NomeAgrupador = x.gp_nome_agrupador })
        //            .ToList();
        //        }
        //    }
        //    catch (Exception x)
        //    {
        //        LogErros.EscreverArquivoDeLog($"{DateTime.Now} - Erro ao Buscar Grupo - | {x.Message} | {x.StackTrace}");

        //        MensagemErros.ErroAoBuscarGrupo(x);
        //    }
        //}

        private void btnFechar_Click(object sender, EventArgs e)
        {
            VerificacaoFecharTela();
        }

        private void btnCancelar_Click(object sender, EventArgs e)
        {
            VerificacaoFecharTela();
        }

        private void btnAcessarGrupoSubGrupo_Click(object sender, EventArgs e)
        {
            frmCadastroGrupoAgrupador frmCadastroGrupoSubGrupo = new frmCadastroGrupoAgrupador(this);
            frmCadastroGrupoSubGrupo.ShowDialog();
        }

        private void btnSalvar_Click(object sender, EventArgs e)
        {
            Salvar();
        }

        private void Salvar()
        {
            if (IsNomeProdutoComMesmoFornecedorJaCadastrado() == false &&
                IsCodigoDeprodutoJaCadastrado() == false &&
                IsCodigoDeBarrasJaCadastrado() == false &&
                IsTodosTextBoxForamPreenchidos() == true)
            {
                ConexaoSalvar();

                if (txtCodigoDeBarras.Text == string.Empty)
                {
                    GerarCodigoDeBarras();
                }

                LimparCampos.LimpaCampos(this.Controls);
            }
        }

        private bool IsCodigoDeBarrasJaCadastrado()
        {
            try
            {
                using (SistemaDeGerenciamento2_0Entities7 db = new SistemaDeGerenciamento2_0Entities7())
                {
                    var IsExisteCodigoDeBarrasProduto = db.tb_produto.Where(x => x.pd_codigo_barras.Equals(txtCodigoDeBarras.Text)).Any();

                    if (IsExisteCodigoDeBarrasProduto == true)
                    {
                        MensagemAtencao.MensagemJaExistente("Codigo de Barras");
                    }

                    return IsExisteCodigoDeBarrasProduto;
                }
            }
            catch (Exception x)
            {
                LogErros.EscreverArquivoDeLog($"{DateTime.Now} - Erro ao Buscar Codigo de Barras - | {x.Message} | {x.StackTrace}");

                MensagemErros.ErroAoBuscarCodigoDeBarrasProduto(x);

                return false;
            }
        }

        private void VerificarSeValoresSaoPositivos(decimal _valor, DevExpress.XtraEditors.TextEdit _textBox)
        {
            if (_valor < 0)
            {
                _textBox.BackColor = Color.LightGray;

                MensagemAtencao.MensagemNaoAceitoValoresNegativos();

                _textBox.Focus();
            }
            else
            {
                _textBox.BackColor = Color.FromArgb(0, 255, 255, 255);
            }
        }

        private void GerarCodigoDeBarras()
        {
            int codigoDeClassificacao = 7896202;

            int codigoEditavel = 52353;

            int codigoFixo = 8;

            string codigoDeBarras = ($"{codigoDeClassificacao}{codigoDeClassificacao + idProduto}{codigoFixo}");

            txtCodigoDeBarras.Text = codigoDeBarras;

            AtualizarCodigoDeBarras(codigoDeBarras);
        }

        private void AtualizarCodigoDeBarras(string _codigoDeBarras)
        {
            try
            {
                using (SistemaDeGerenciamento2_0Entities7 db = new SistemaDeGerenciamento2_0Entities7())
                {
                    var codigoDeBarrasProduto = db.tb_produto.FirstOrDefault(x => x.id_produto.Equals(idProduto));

                    codigoDeBarrasProduto.pd_codigo_barras = _codigoDeBarras;

                    db.SaveChanges();
                }
            }
            catch (Exception x)
            {
                LogErros.EscreverArquivoDeLog($"{DateTime.Now} - Erro ao Atualizar Codigo de Barras - | {x.Message} | {x.StackTrace}");

                MensagemErros.ErroAoCadastroCodigoDeBarrasProduto(x);
            }
        }

        //private class FornecedorClass
        //{
        //    public int ID { get; set; }
        //    public string CNPJ { get; set; }
        //    public string NomeFantasia { get; set; }
        //}

        //private async Task BuscarDadosParaPreencherComboBoxFornecedor()
        //{
        //    try
        //    {
        //        using (SistemaDeGerenciamento2_0Entities5 db = new SistemaDeGerenciamento2_0Entities5())
        //        {
        //            ListaForncedor = db.tb_registro.Where(x => x.rg_tipo_cadastro.Equals("Fornecedor"))
        //                .Select(x => new FornecedorClass { ID = x.id_registro, CNPJ = x.rg_cnpj, NomeFantasia = x.rg_nome_fantasia }).ToList();
        //        }
        //    }
        //    catch (Exception x)
        //    {
        //        MessageBox.Show(x.ToString());
        //    }
        //}

        //private void PreenchimentoComboBoxFornecedor()
        //{
        //    cmbFornecedor.Properties.DataSource = ListaForncedor;
        //    cmbFornecedor.Properties.DisplayMember = "CNPJ";
        //    cmbFornecedor.Properties.ValueMember = "ID";
        //}

        private bool IsNomeProdutoComMesmoFornecedorJaCadastrado()
        {
            try
            {
                using (SistemaDeGerenciamento2_0Entities7 db = new SistemaDeGerenciamento2_0Entities7())
                {
                    int valor = Convert.ToInt32(cmbFornecedor.Properties.GetKeyValueByDisplayValue(cmbFornecedor.Text));

                    var IsExisteNomeProdutoEFornecedor = db.tb_produto.Where(x => x.pd_nome.Equals(txtNome.Text)).Any();

                    if (IsExisteNomeProdutoEFornecedor == true)
                    {
                        MensagemAtencao.MensagemProdutoJaExistente();
                    }

                    return IsExisteNomeProdutoEFornecedor;
                }
            }
            catch (Exception x)
            {
                LogErros.EscreverArquivoDeLog($"{DateTime.Now} - Erro ao Buscar Nome do Produto e Fornecedor - | {x.Message} | {x.StackTrace}");

                MensagemErros.ErroAoBuscarNomeDoProdutoEFornecedor(x);

                return false;
            }
        }

        private void txtCusto_KeyUp(object sender, KeyEventArgs e)
        {
            if (txtCusto.Text != string.Empty && txtCusto.Text != "R$ 0,00" && txtCusto.Text != "R$ " && txtCusto.Text != "R$" && txtCusto.Text != "R")
            {
                CalcularPreco();
            }
        }

        private void txtMargemLucro_KeyUp(object sender, KeyEventArgs e)
        {
            if (txtMargemLucro.Text != string.Empty)
            {
                CalcularPreco();
            }
            else
            {
                txtPreco.Text = txtCusto.Text;
            }
        }

        private void txtPreco_KeyUp(object sender, KeyEventArgs e)
        {
            if (txtPreco.Text != string.Empty && txtPreco.Text != "R$ 0,00" && txtPreco.Text != "R$ " && txtPreco.Text != "R$" && txtPreco.Text != "R")
            {
                CalcularMargemLucro();
            }
        }

        private void txtCodigo_KeyPress(object sender, KeyPressEventArgs e)
        {
            ManipulacaoTextBox.DigitarApenasLetrasOuNumeros(e, txtCodigo);
        }

        private void frmCadastroProduto_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Escape)
            {
                VerificacaoFecharTela();
            }
            else if (e.KeyCode == Keys.F10)
            {
                Salvar();
            }
        }

        private void frmCadastroProduto_MouseMove(object sender, MouseEventArgs e)
        {
            if (e.Button != MouseButtons.Left) return;
            this.Left = X + MousePosition.X;
            this.Top = Y + MousePosition.Y;
        }

        private void frmCadastroProduto_MouseDown(object sender, MouseEventArgs e)
        {
            if (e.Button != MouseButtons.Left) return;
            X = this.Left - MousePosition.X;
            Y = this.Top - MousePosition.Y;
        }

        private void VerificacaoFecharTela()
        {
            if (txtNome.Text != string.Empty || cmbGrupo.Text != string.Empty || cmbFinalidade.Text != string.Empty ||
                  cmbTipoProduto.Text != string.Empty)
            {
                MensagemAtencao.MensagemCancelar(this);
            }
            else
            {
                this.Close();
            }
        }

        //private void PreenchimentoComboBoxGrupo()
        //{
        //    cmbGrupo.Properties.DataSource = ListaGrupoAgrupador;
        //    cmbGrupo.Properties.DisplayMember = "NomeGrupo";
        //    cmbGrupo.Properties.ValueMember = "IDGrupo";
        //}

        private bool IsTodosTextBoxForamPreenchidos()
        {
            if (txtNome.Text != string.Empty && cmbGrupo.Text != string.Empty && cmbFinalidade.Text != string.Empty &&
                cmbTipoProduto.Text != string.Empty && txtTipoUnidade.Text != "Ex.: Peça, Un, Kg")
            {
                CorFundoTextBox(Color.FromArgb(0, 255, 255, 255));

                return true;
            }
            else
            {
                CorFundoTextBox(Color.LightGray);

                MensagemAtencao.MensagemPreencherCampos();

                return false;
            }
        }

        private bool IsCodigoDeprodutoJaCadastrado()
        {
            try
            {
                using (SistemaDeGerenciamento2_0Entities7 db = new SistemaDeGerenciamento2_0Entities7())
                {
                    var IsExistecodigoProduto = db.tb_produto.Where(x => x.pd_codigo.Equals(txtCodigo.Text)).Any();

                    if (IsExistecodigoProduto == true)
                    {
                        MensagemAtencao.MensagemProdutoJaExistente();
                    }
                    return IsExistecodigoProduto;
                }
            }
            catch (Exception x)
            {
                LogErros.EscreverArquivoDeLog($"{DateTime.Now} - Erro ao Buscar Codigo Produto - | {x.Message} | {x.StackTrace}");

                MensagemErros.ErroAoBuscarCodigoDeProduto(x);

                return false;
            }
        }

        private void CorFundoTextBox(Color corFundo)
        {
            txtCodigo.BackColor = corFundo;
            cmbFinalidade.BackColor = corFundo;
            txtNome.BackColor = corFundo;
            cmbGrupo.BackColor = corFundo;
            cmbFornecedor.BackColor = corFundo;
            txtTipoUnidade.BackColor = corFundo;
            cmbTipoProduto.BackColor = corFundo;
            txtCusto.BackColor = corFundo;
            txtMargemLucro.BackColor = corFundo;
            txtPreco.BackColor = corFundo;
            txtEstoqueMinimo.BackColor = corFundo;
        }

        private void ConexaoSalvar()
        {
            try
            {
                using (SistemaDeGerenciamento2_0Entities7 db = new SistemaDeGerenciamento2_0Entities7())
                {
                    var CadastroProduto = new tb_produto()
                    {
                        pd_codigo = txtCodigo.Text,
                        pd_codigo_barras = txtCodigoDeBarras.Text,
                        pd_finalidade = cmbFinalidade.Text,
                        pd_nome = txtNome.Text,
                        pd_estoque_minimo = Convert.ToDecimal(txtEstoqueMinimo.Text),
                        pd_custo = Convert.ToDecimal(txtCusto.Text.Replace("R$ ", string.Empty)),
                        pd_margem = Convert.ToDecimal(txtMargemLucro.Text.Replace("%", string.Empty)),
                        pd_preco = Convert.ToDecimal(txtPreco.Text.Replace("R$ ", string.Empty)),
                        pd_tipo_produto = cmbTipoProduto.Text,
                        pd_tipo_unidade = txtTipoUnidade.Text,
                        pd_observacoes = txtObservacoes.Text,
                        fk_grupo = Convert.ToInt32(cmbGrupo.Properties.GetKeyValueByDisplayValue(cmbGrupo.Text)),
                        fk_registro_forncedor = Convert.ToInt32(cmbFornecedor.Properties.GetKeyValueByDisplayValue(cmbFornecedor.Text)),
                    };

                    db.tb_produto.Add(CadastroProduto);
                    db.SaveChanges();

                    idProduto = CadastroProduto.id_produto;

                    ChamandoAlertaSucessoNoCantoInferiorDireito();
                }
            }
            catch (Exception x)
            {
                LogErros.EscreverArquivoDeLog($"{DateTime.Now} - Erro ao Cadastrar Produto - | {x.Message} | {x.StackTrace}");

                MensagemErros.ErroAoCadastroProduto(x);
            }
        }

        private void ChamandoAlertaSucessoNoCantoInferiorDireito()
        {
            DadosMensagemAlerta msg = new DadosMensagemAlerta("\n   Sucesso!", Resources.salvar_verde50);
            AlertaSalvar.Show(this, $"{msg.titulo}", msg.texto, string.Empty, msg.image, msg);
        }

        private void CalcularPreco()
        {
            if (Convert.ToDecimal(txtCusto.Text.Replace("R$ ", "")) > 0)
            {
                decimal valorCusto = Convert.ToDecimal(txtCusto.Text.Replace("R$", string.Empty));

                decimal margemLucro = Convert.ToDecimal(txtMargemLucro.Text.Replace("%", string.Empty));

                decimal valorPreco = 0;

                valorPreco = (valorCusto * margemLucro / 100) + valorCusto;

                txtPreco.Text = valorPreco.ToString("C");
            }
        }

        private void CalcularMargemLucro()
        {
            if (Convert.ToDecimal(txtPreco.Text.Replace("R$ ", "")) > 0)
            {
                decimal valorCusto = Convert.ToDecimal(txtCusto.Text.Replace("R$", string.Empty));

                decimal valorPreco = Convert.ToDecimal(txtPreco.Text.Replace("R$", string.Empty)); ;

                decimal margemLucro = 0;

                if (valorCusto > 0)
                {
                    margemLucro = ((valorPreco * 100) / valorCusto) / 100;

                    txtMargemLucro.Text = (margemLucro - 1).ToString("P");
                }
            }
        }

        private void txtNome_KeyPress(object sender, KeyPressEventArgs e)
        {
            ManipulacaoTextBox.DigitarApenasLetras(e, txtNome);
        }

        private void cmbFinalidade_KeyPress(object sender, KeyPressEventArgs e)
        {
            ManipulacaoTextBox.DigitarApenasLetras(e, cmbFinalidade);
        }

        private void cmbTipoProduto_KeyPress(object sender, KeyPressEventArgs e)
        {
            ManipulacaoTextBox.DigitarApenasLetras(e, cmbTipoProduto);
        }

        private void txtCusto_Leave(object sender, EventArgs e)
        {
            decimal valor = Convert.ToDecimal(txtCusto.Text.Replace("R$ ", ""));

            VerificarSeValoresSaoPositivos(valor, txtCusto);
        }

        private void txtPreco_Leave(object sender, EventArgs e)
        {
            decimal valor = Convert.ToDecimal(txtPreco.Text.Replace("R$ ", ""));

            VerificarSeValoresSaoPositivos(valor, txtPreco);
        }

        private void txtEstoqueMinimo_Leave(object sender, EventArgs e)
        {
            decimal valor = Convert.ToDecimal(txtEstoqueMinimo.Text);

            VerificarSeValoresSaoPositivos(valor, txtEstoqueMinimo);
        }

        private void txtMargemLucro_Leave(object sender, EventArgs e)
        {
            decimal valor = Convert.ToDecimal(txtMargemLucro.Text.Replace("%", ""));

            VerificarSeValoresSaoPositivos(valor, txtMargemLucro);
        }
    }
}