using DevExpress.XtraEditors;
using SistemaDeGerenciamento2_0.Context;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SistemaDeGerenciamento2_0.Forms
{
    public partial class frmFaturamentoPorDia : DevExpress.XtraEditors.XtraForm
    {
        public frmFaturamentoPorDia()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            teste();
            //string query = "   select tb_nota_fiscal_saida.nfs_data_emissao," +
            //    "	   sum(tb_nota_fiscal_saida.nfs_quantidade)," +
            //    " sum(tb_nota_fiscal_saida.nfs_valor_parcial) " +
            //    "     from dbo.tb_nota_fiscal_saida" +
            //    "       tb_nota_fiscal_saida" +
            //    "	   group by tb_nota_fiscal_saida.nfs_data_emissao" +
            //    "	   order by tb_nota_fiscal_saida.nfs_data_emissao where tb_nota_fiscal_saida.nfs_data_emissao == '20/01/2023'";

            //sqlDataSource1.Queries

            //string query = "SELECT * FROM tabela WHERE campo = 'valor'";
            //sqlDataSource1..SelectCommand = query;
            //gridControl4.DataSource = sqlDataSource1;
            //gridView4.DataBind();

            //using (SistemaDeGerenciamento2_0Context context = new SistemaDeGerenciamento2_0Context())
            //{
            //    //string valor = "valor";
            //    var query = context.tb_nota_fiscal_saida.Where(x => x.nfs_data_emissao == Convert.ToDateTime("28/01/2023")).ToList();
            //    gridView4.DataSource = query;
            //    //gridView4.DataBind();

            //}
        }

        private List<string> lista = new List<string>();

        private void PreencherLista()
        {
            lista.Add("israel1");
            lista.Add("israel2");
            lista.Add("israel3");
            lista.Add("israel4");
            lista.Add("israel5");
        }

        private List<string> teste()
        {
            PreencherLista();

            List<string> lista2 = new List<string>();

            foreach (var item in lista)
            {
                lista2.Add(item);
            }

            return lista2;
        }
    }
}