using DevExpress.XtraEditors;
using DevExpress.XtraSplashScreen;
using SistemaDeGerenciamento2_0.Class;
using SistemaDeGerenciamento2_0.Context;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SistemaDeGerenciamento2_0.Forms
{
    public partial class frmFaturamentoPorVendedor : DevExpress.XtraEditors.XtraForm
    {
        private int X = 0;
        private int Y = 0;

        private DataTable dt = new DataTable();

        private frmCalendario frmCalendario;

        private frmTelaPrincipal frmTelaPrincipal;

        public bool IsPreencherGrid = false;
        public bool IsCalendarioAberto = false;

        public DateTime dataInicial = DateTime.Today;
        public DateTime dataFinal = DateTime.Today;

        public frmFaturamentoPorVendedor(frmTelaPrincipal _frmTelaPrincipal)
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();

            frmTelaPrincipal = _frmTelaPrincipal;

            PreencherData();
        }

        private void PreencherData()
        {
            dataInicial = new DateTime(DateTime.Today.Year, DateTime.Today.Month, 1);

            dataFinal = new DateTime(DateTime.Today.Year, DateTime.Today.Month, DateTime.DaysInMonth(DateTime.Today.Year, DateTime.Today.Month));

            txtCalendario.Text = $"{dataInicial.ToShortDateString()} - {dataFinal.ToShortDateString()}";
        }

        private void ReloadDataConfigUsuario()
        {
            using (var handle = SplashScreenManager.ShowOverlayForm(this))
            {
                PreencherGrid();
            }
        }

        private void btnFechar_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void CriandoColunasGrid()
        {
            dt.Clear();
            dt.Columns.Clear();

            dt.Columns.Add("Data");
            dt.Columns.Add("Dia Semana");
            dt.Columns.Add("Quantidade Total");
            dt.Columns.Add("Valor Total Produto");
        }

        private void PreencherGrid()
        {
            CriandoColunasGrid();

            try
            {
                SistemaDeGerenciamento2_0Context db = new SistemaDeGerenciamento2_0Context();

                var result = db.tb_nota_fiscal_saida
                    .Where(x => x.nfs_vendedor == cmbVendedor.Text && x.nfs_data_emissao >= dataInicial && x.nfs_data_emissao <= dataFinal)
                    .GroupBy(x => x.nfs_data_emissao)
                    .OrderBy(x => x.Key)
                    .Select(g => new
                    {
                        DataEmissao = g.Key,
                        TotalQuantidade = g.Sum(x => x.nfs_quantidade),
                        TotalValorPago = g.Sum(x => x.nfs_valor_pago)
                    }).ToList();

                decimal valorTotal = 0;
                decimal quantidadeTotal = 0;

                foreach (var item in result)
                {
                    string diaSemana = TraduzindoDiaDaSemana(item.DataEmissao.DayOfWeek.ToString());
                    string data = item.DataEmissao.ToShortDateString();
                    string quantidade = item.TotalQuantidade.ToString("N0");
                    string valor = item.TotalValorPago.ToString("C2");

                    dt.Rows.Add(data, diaSemana, quantidade, valor);

                    valorTotal += item.TotalQuantidade;
                    quantidadeTotal += item.TotalValorPago;
                }

                lblQuantidadeTotal.Text = valorTotal.ToString("N0");
                lblValorTotal.Text = quantidadeTotal.ToString("C2");

                gridControl1.DataSource = dt;
                gridControl1.Refresh();
            }
            catch (Exception x)
            {
                LogErros.EscreverArquivoDeLog($"{DateTime.Now} - Erro ao Buscar Dados Relatorio por Vendedor - Relatorio - Faturamento por Vendedor | {x.Message} | {x.StackTrace}");

                MensagemErros.ErroAoBuscarDadosFaturamentoPorVendedor(x);
            }
        }

        private string TraduzindoDiaDaSemana(string _dia)
        {
            switch (_dia)
            {
                case "Monday":

                    return "Segunda-Feira";

                case "Tuesday":

                    return "Terça-Feira";

                case "Wednesday":

                    return "Quarta-Feira";

                case "Thursday":

                    return "Quinta-Feira";

                case "Friday":

                    return "Sexta-Feira";

                case "Saturday":

                    return "Sábado";

                case "Sunday":

                    return "Domingo";
            }

            return string.Empty;
        }

        private void cmbVendedor_TextChanged(object sender, EventArgs e)
        {
            ReloadDataConfigUsuario();
            //PreencherGrid();
        }

        private void frmFaturamentoPorVendedor_MouseDown(object sender, MouseEventArgs e)
        {
            if (e.Button != MouseButtons.Left) return;
            X = this.Left - MousePosition.X;
            Y = this.Top - MousePosition.Y;
        }

        private void frmFaturamentoPorVendedor_MouseMove(object sender, MouseEventArgs e)
        {
            if (e.Button != MouseButtons.Left) return;
            this.Left = X + MousePosition.X;
            this.Top = Y + MousePosition.Y;
        }

        private void frmFaturamentoPorVendedor_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Escape)
            {
                this.Close();
            }
        }

        private void txtCalendario_Enter(object sender, EventArgs e)
        {
            ExibirCalendario();
        }

        private void txtCalendario_Click(object sender, EventArgs e)
        {
            FechandoTela();

            ExibirCalendario();
        }

        private void FechandoTela()
        {
            if (IsPreencherGrid == true)
            {
                PreencherGrid();
            }

            IsPreencherGrid = false;

            frmCalendario.Close();
        }

        private void ExibirCalendario()
        {
            frmCalendario = new frmCalendario(this);
            frmCalendario.StartPosition = FormStartPosition.Manual;
            frmCalendario.Location = new Point(480, 220);
            frmCalendario.Show();
        }

        private void frmFaturamentoPorVendedor_Click(object sender, EventArgs e)
        {
            if (IsCalendarioAberto == true)
            {
                PreencherGridFecharCalendario();
            }

            //FechandoTela();
        }

        private void PreencherGridFecharCalendario()
        {
            txtCalendario.Text = $"{dataInicial.ToShortDateString()} - {dataFinal.ToShortDateString()}";

            dataInicial = Convert.ToDateTime(frmCalendario.txtDataInicial.Text);
            dataFinal = Convert.ToDateTime(frmCalendario.txtDataFinal.Text);

            PreencherGrid();

            frmCalendario.Close();

            gridControl1.Focus();

            IsCalendarioAberto = false;
        }

        private void btnCalendario_Click(object sender, EventArgs e)
        {
            ExibirCalendario();
        }

        private void txtCalendario_Leave(object sender, EventArgs e)
        {
            FechandoTela();
        }
    }
}