//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGerenciamento2_0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cadastro_despesa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cadastro_despesa()
        {
            this.tb_repeticao_despesa = new HashSet<tb_repeticao_despesa>();
        }
    
        public int id_categoria_despesa { get; set; }
        public string cd_categoria_agrupadora { get; set; }
        public string cd_categoria { get; set; }
        public string cd_tipo_custo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_repeticao_despesa> tb_repeticao_despesa { get; set; }
    }
}
