//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGerenciamento2_0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_configuracao_financeira
    {
        public int id_configuracao_financeira { get; set; }
        public decimal cf_juros_dia { get; set; }
        public decimal cf_multa_porcentagem { get; set; }
        public decimal cf_multa_fixa { get; set; }
        public decimal cf_carencia { get; set; }
        public decimal cf_desconto { get; set; }
    }
}
