//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGerenciamento2_0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_configuracao_financeira
    {
        public int id_configuracao_financeira { get; set; }
        public Nullable<decimal> cf_juros_dia { get; set; }
        public Nullable<decimal> cf_parcela_juros { get; set; }
        public Nullable<decimal> cf_desconto_pagamento { get; set; }
        public Nullable<decimal> cf_desconto_grupo_produto { get; set; }
        public Nullable<int> fk_grupo { get; set; }
    
        public virtual tb_grupo tb_grupo { get; set; }
    }
}
