//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGerenciamento2_0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_enderecos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_enderecos()
        {
            this.tb_registro = new HashSet<tb_registro>();
        }
    
        public int id_endereco { get; set; }
        public string ed_tipo { get; set; }
        public string ed_cep { get; set; }
        public string ed_estado { get; set; }
        public string ed_locgradouro { get; set; }
        public string ed_numero { get; set; }
        public string ed_complemento { get; set; }
        public string ed_bairro { get; set; }
        public string ed_cidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_registro> tb_registro { get; set; }
    }
}
