//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGerenciamento2_0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_informacoes_comeciais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_informacoes_comeciais()
        {
            this.tb_registro = new HashSet<tb_registro>();
        }
    
        public int id_informacao_comercial { get; set; }
        public string ic_situacao { get; set; }
        public string ic_prioridade { get; set; }
        public string ic_vendedor { get; set; }
        public decimal ic_limite_credito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_registro> tb_registro { get; set; }
    }
}
