//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGerenciamento2_0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_nota_fiscal_saida
    {
        public int id_nota_fiscal_saida { get; set; }
        public int nfs_numero_nf_saida { get; set; }
        public System.DateTime nfs_data_emissao { get; set; }
        public decimal nfs_quantidade { get; set; }
        public decimal nfs_valor_total_parcial { get; set; }
        public decimal nfs_valor_pago { get; set; }
        public Nullable<decimal> nfs_valor_juros { get; set; }
        public Nullable<decimal> nfs_valor_desconto { get; set; }
        public string nfs_vendedor { get; set; }
        public Nullable<int> fk_estoque { get; set; }
        public Nullable<int> fk_registro_cliente { get; set; }
    
        public virtual tb_estoque tb_estoque { get; set; }
        public virtual tb_registro tb_registro { get; set; }
    }
}
