//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGerenciamento2_0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_nota_fiscal_entrada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_nota_fiscal_entrada()
        {
            this.tb_estoque = new HashSet<tb_estoque>();
        }
    
        public int id_nota_fiscal_entrada { get; set; }
        public int nfe_numero_nf_entrada { get; set; }
        public decimal nfe_quantidade { get; set; }
        public string nfe_codigo_produto { get; set; }
        public int nfe_indice { get; set; }
        public string nfe_cnpj { get; set; }
        public string nfe_razao_social { get; set; }
        public string nfe_descricao_social { get; set; }
        public string nfe_unidade { get; set; }
        public decimal nfe_valor_unitario { get; set; }
        public decimal nfe_valor_total { get; set; }
        public System.DateTime nfe_data_emissao { get; set; }
        public System.DateTime nfe_data_lancamento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_estoque> tb_estoque { get; set; }
    }
}
