//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGerenciamento2_0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_produto()
        {
            this.tb_estoque = new HashSet<tb_estoque>();
        }
    
        public int id_produto { get; set; }
        public string pd_codigo { get; set; }
        public string pd_codigo_barras { get; set; }
        public string pd_finalidade { get; set; }
        public string pd_nome { get; set; }
        public decimal pd_estoque_minimo { get; set; }
        public decimal pd_custo { get; set; }
        public decimal pd_margem { get; set; }
        public decimal pd_preco { get; set; }
        public string pd_tipo_produto { get; set; }
        public string pd_tipo_unidade { get; set; }
        public string pd_observacoes { get; set; }
        public int fk_grupo { get; set; }
        public Nullable<int> fk_registro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_estoque> tb_estoque { get; set; }
        public virtual tb_grupo tb_grupo { get; set; }
        public virtual tb_registro tb_registro { get; set; }
    }
}
