//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGerenciamento2_0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_permissoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_permissoes()
        {
            this.tb_registro = new HashSet<tb_registro>();
        }
    
        public int id_permissoes { get; set; }
        public bool pm_acesso_pdv { get; set; }
        public bool pm_vendas_do_dias { get; set; }
        public bool pm_receber_conta { get; set; }
        public bool pm_todas_vendas { get; set; }
        public bool pm_editar_venda { get; set; }
        public bool pm_remover_venda { get; set; }
        public bool pm_cancelar_venda { get; set; }
        public bool pm_realizar_devolucao { get; set; }
        public bool pm_alerta_contas_atrasadas { get; set; }
        public bool pm_visualizar_lancamentos { get; set; }
        public bool pm_visualizar_contas_pagar { get; set; }
        public bool pm_visualizar_contas_receber { get; set; }
        public bool pm_receber_contas { get; set; }
        public bool pm_pagar_contas { get; set; }
        public bool pm_visualizar_fluxo_caixa { get; set; }
        public bool pm_visualizar_lancamento_faturamento { get; set; }
        public bool pm_ajustar_configuracao_geral { get; set; }
        public bool pm_editar_categoria { get; set; }
        public bool pm_criar_editar_usuario { get; set; }
        public bool pm_visualizar_visao_geral { get; set; }
        public bool pm_visualizar_dre { get; set; }
        public bool pm_criar_visualizar_relatorios { get; set; }
        public bool pm_adicionar_produto { get; set; }
        public bool pm_editar_produto { get; set; }
        public bool pm_remover_produto { get; set; }
        public bool pm_filtrar_produto { get; set; }
        public bool pm_alerta_estoque_baixo { get; set; }
        public bool pm_tabela_produtos_removidos { get; set; }
        public bool pm_efetuar_cadastro { get; set; }
        public bool pm_editar_cadastro { get; set; }
        public bool pm_remover_cadastro { get; set; }
        public bool pm_visualizar_cadastro_completo { get; set; }
        public bool pm_editar_cretido_cadastro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_registro> tb_registro { get; set; }
    }
}
