//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGerenciamento2_0
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_registro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_registro()
        {
            this.tb_despesa = new HashSet<tb_despesa>();
            this.tb_nota_fiscal_saida = new HashSet<tb_nota_fiscal_saida>();
            this.tb_produto = new HashSet<tb_produto>();
            this.tb_repeticao_despesa = new HashSet<tb_repeticao_despesa>();
        }
    
        public int id_registro { get; set; }
        public string rg_tipo_cadastro { get; set; }
        public string rg_categoria { get; set; }
        public string rg_cpf { get; set; }
        public string rg_nome { get; set; }
        public string rg_sexo { get; set; }
        public string rg_rg { get; set; }
        public Nullable<System.DateTime> rg_data_nascimento { get; set; }
        public System.DateTime rg_data_cadastro { get; set; }
        public string rg_observacoes { get; set; }
        public string rg_login { get; set; }
        public string rg_senha { get; set; }
        public string rg_cnpj { get; set; }
        public string rg_nome_fantasia { get; set; }
        public string rg_razao_social { get; set; }
        public string rg_email_xml { get; set; }
        public string rg_inscricao_estadual { get; set; }
        public string rg_inscricao_municipal { get; set; }
        public string rg_email { get; set; }
        public string rg_celular { get; set; }
        public string rg_telefone_fixo { get; set; }
        public Nullable<int> fk_permissoes { get; set; }
        public Nullable<int> fk_informacao_comercial { get; set; }
        public Nullable<int> fk_endereco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_despesa> tb_despesa { get; set; }
        public virtual tb_enderecos tb_enderecos { get; set; }
        public virtual tb_informacoes_comeciais tb_informacoes_comeciais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_nota_fiscal_saida> tb_nota_fiscal_saida { get; set; }
        public virtual tb_permissoes tb_permissoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_produto> tb_produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_repeticao_despesa> tb_repeticao_despesa { get; set; }
    }
}
