// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaDeGerenciamento2_0.Models
{
    public partial class tb_configuracao_financeira
    {
        [Key]
        public int id_configuracao_financeira { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? cf_juros_dia { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? cf_parcela_juros { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? cf_desconto_pagamento { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? cf_desconto_grupo_produto { get; set; }
        public int? fk_grupo { get; set; }

        [ForeignKey(nameof(fk_grupo))]
        [InverseProperty(nameof(tb_grupo.tb_configuracao_financeira))]
        public virtual tb_grupo fk_grupoNavigation { get; set; }
    }
}