// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaDeGerenciamento2_0.Models
{
    public partial class tb_estoque
    {
        public tb_estoque()
        {
            tb_nota_fiscal_saida = new HashSet<tb_nota_fiscal_saida>();
        }

        [Key]
        public int id_estoque { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal ep_quantidade { get; set; }
        [Column(TypeName = "date")]
        public DateTime ep_data_entrada { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ep_data_exclusao { get; set; }
        [Required]
        [StringLength(255)]
        public string ep_codigo_barras { get; set; }
        [StringLength(255)]
        public string ep_status_situacao { get; set; }
        public int fk_produto { get; set; }
        public int fk_nota_fiscal_entrada { get; set; }

        [ForeignKey(nameof(fk_nota_fiscal_entrada))]
        [InverseProperty(nameof(tb_nota_fiscal_entrada.tb_estoque))]
        public virtual tb_nota_fiscal_entrada fk_nota_fiscal_entradaNavigation { get; set; }
        [ForeignKey(nameof(fk_produto))]
        [InverseProperty(nameof(tb_produto.tb_estoque))]
        public virtual tb_produto fk_produtoNavigation { get; set; }
        [InverseProperty("fk_estoqueNavigation")]
        public virtual ICollection<tb_nota_fiscal_saida> tb_nota_fiscal_saida { get; set; }
    }
}