// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaDeGerenciamento2_0.Models
{
    public partial class tb_grupo
    {
        public tb_grupo()
        {
            tb_configuracao_financeira = new HashSet<tb_configuracao_financeira>();
            tb_produto = new HashSet<tb_produto>();
        }

        [Key]
        public int id_grupo { get; set; }
        [StringLength(255)]
        public string gp_nome_grupo { get; set; }
        [Required]
        [StringLength(255)]
        public string gp_nome_agrupador { get; set; }

        [InverseProperty("fk_grupoNavigation")]
        public virtual ICollection<tb_configuracao_financeira> tb_configuracao_financeira { get; set; }
        [InverseProperty("fk_grupoNavigation")]
        public virtual ICollection<tb_produto> tb_produto { get; set; }
    }
}