// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaDeGerenciamento2_0.Models
{
    public partial class tb_informacoes_comerciais
    {
        public tb_informacoes_comerciais()
        {
            tb_registro = new HashSet<tb_registro>();
        }

        [Key]
        public int id_informacao_comercial { get; set; }
        [Required]
        [StringLength(255)]
        public string ic_situacao { get; set; }
        [Required]
        [StringLength(255)]
        public string ic_prioridade { get; set; }
        [Required]
        [StringLength(255)]
        public string ic_vendedor { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal ic_limite_credito { get; set; }

        [InverseProperty("fk_informacao_comercialNavigation")]
        public virtual ICollection<tb_registro> tb_registro { get; set; }
    }
}