// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaDeGerenciamento2_0.Models
{
    public partial class tb_nota_fiscal_entrada
    {
        public tb_nota_fiscal_entrada()
        {
            tb_estoque = new HashSet<tb_estoque>();
        }

        [Key]
        public int id_nota_fiscal_entrada { get; set; }
        public int nfe_numero_nf_entrada { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal nfe_quantidade { get; set; }
        [Required]
        [StringLength(255)]
        public string nfe_codigo_produto { get; set; }
        public int nfe_indice { get; set; }
        [Required]
        [StringLength(255)]
        public string nfe_cnpj { get; set; }
        [Required]
        [StringLength(255)]
        public string nfe_razao_social { get; set; }
        [Required]
        [StringLength(255)]
        public string nfe_descricao_social { get; set; }
        [Required]
        [StringLength(255)]
        public string nfe_unidade { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal nfe_valor_unitario { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal nfe_valor_total { get; set; }
        [Column(TypeName = "date")]
        public DateTime nfe_data_emissao { get; set; }
        [Column(TypeName = "date")]
        public DateTime nfe_data_lancamento { get; set; }

        [InverseProperty("fk_nota_fiscal_entradaNavigation")]
        public virtual ICollection<tb_estoque> tb_estoque { get; set; }
    }
}