// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaDeGerenciamento2_0.Models
{
    public partial class tb_produto
    {
        public tb_produto()
        {
            tb_estoque = new HashSet<tb_estoque>();
        }

        [Key]
        public int id_produto { get; set; }
        [Required]
        [StringLength(255)]
        public string pd_codigo { get; set; }
        [Required]
        [StringLength(255)]
        public string pd_finalidade { get; set; }
        [Required]
        [StringLength(255)]
        public string pd_nome { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal pd_estoque_minimo { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal pd_custo { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal pd_margem { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal pd_preco { get; set; }
        [Required]
        [StringLength(255)]
        public string pd_observacoes { get; set; }
        public int fk_grupo { get; set; }
        public int? fk_registro_forncedor { get; set; }
        [Required]
        [StringLength(255)]
        public string pd_codigo_barras { get; set; }
        [Required]
        [StringLength(255)]
        public string pd_tipo_produto { get; set; }
        [Required]
        [StringLength(255)]
        public string pd_tipo_unidade { get; set; }
        [StringLength(255)]
        public string pd_usuario_cadastrador { get; set; }

        [ForeignKey(nameof(fk_grupo))]
        [InverseProperty(nameof(tb_grupo.tb_produto))]
        public virtual tb_grupo fk_grupoNavigation { get; set; }
        [ForeignKey(nameof(fk_registro_forncedor))]
        [InverseProperty(nameof(tb_registro.tb_produto))]
        public virtual tb_registro fk_registro_forncedorNavigation { get; set; }
        [InverseProperty("fk_produtoNavigation")]
        public virtual ICollection<tb_estoque> tb_estoque { get; set; }
    }
}