// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaDeGerenciamento2_0.Models
{
    public partial class tb_repeticao_despesa
    {
        public tb_repeticao_despesa()
        {
            tb_despesa = new HashSet<tb_despesa>();
        }

        [Key]
        public int id_repeticao_despesas { get; set; }
        [Column(TypeName = "date")]
        public DateTime rp_data_inicial { get; set; }
        [Column(TypeName = "date")]
        public DateTime rp_data_final { get; set; }
        [Required]
        [StringLength(255)]
        public string rp_periodicidade { get; set; }
        [Required]
        [StringLength(255)]
        public string rp_observacao { get; set; }
        public int fk_cadastro_despesa { get; set; }

        [ForeignKey(nameof(fk_cadastro_despesa))]
        [InverseProperty(nameof(tb_cadastro_despesa.tb_repeticao_despesa))]
        public virtual tb_cadastro_despesa fk_cadastro_despesaNavigation { get; set; }
        [InverseProperty("fk_repeticao_despesaNavigation")]
        public virtual ICollection<tb_despesa> tb_despesa { get; set; }
    }
}